### ISSUE TITLE
Error running war-drive.php

### ISSUE THREAD

**Issue by naturekid72** [sailboat-anon/wifi-pineapple-mark-vii#1]
Don't know if it is me. I configured everything and get this:

> Starting war-driver.php by sailboatanon
> https://github.com/sailboat-anon/ 
> Enabling pineAP (AGGRO settings)
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/jd/wifi-pineapple-war-driver/war-driver.php:149
Stack trace:
#0 /home/jd/wifi-pineapple-war-driver/war-driver.php(191): authenticate()
#1 /home/jd/wifi-pineapple-war-driver/war-driver.php(63): authorized_put('/api/pineap/set...', Array, 'Enabling pineAP...')
#2 /home/jd/wifi-pineapple-war-driver/war-driver.php(67): set_aggro()
#3 /home/jd/wifi-pineapple-war-driver/war-driver.php(43): run_scand()
#4 {main}
  thrown in /home/jd/wifi-pineapple-war-driver/war-driver.php on line 149

**Comment by sailboat-anon** [comment]
sorry -- just seeing this now.  are you still having the issue?

**Comment by JohnFreeman646** [comment]
> sorry -- just seeing this now. are you still having the issue?

I just tried using this and am getting exactly the same error. I am running MK7 FW 1.1.1 and running the script in Kali Linux in WSL

`┌──(root💀IT-Lenovo)-[~/wifi-pineapple-war-driver]
└─# php war-driver.php
> Starting war-driver.php by sailboatanon
> https://github.com/sailboat-anon/
> Enabling pineAP (AGGRO settings)
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/wifi-pineapple-war-driver/war-driver.php:149
Stack trace:
#0 /root/wifi-pineapple-war-driver/war-driver.php(191): authenticate()
#1 /root/wifi-pineapple-war-driver/war-driver.php(63): authorized_put()
#2 /root/wifi-pineapple-war-driver/war-driver.php(67): set_aggro()
#3 /root/wifi-pineapple-war-driver/war-driver.php(43): run_scand()
#4 {main}
  thrown in /root/wifi-pineapple-war-driver/war-driver.php on line 149`

**Comment by JohnFreeman646** [comment]
> > sorry -- just seeing this now. are you still having the issue?
> 
> I just tried using this and am getting exactly the same error. I am running MK7 FW 1.1.1 and running the script in Kali Linux in WSL
> 
> `┌──(root💀IT-Lenovo)-[~/wifi-pineapple-war-driver] └─# php war-driver.php
> 
> > Starting war-driver.php by sailboatanon
> > https://github.com/sailboat-anon/
> > Enabling pineAP (AGGRO settings)
> > PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/wifi-pineapple-war-driver/war-driver.php:149
> > Stack trace:
> > #0 /root/wifi-pineapple-war-driver/war-driver.php(191): authenticate()
> > #1 /root/wifi-pineapple-war-driver/war-driver.php(63): authorized_put()
> > #2 /root/wifi-pineapple-war-driver/war-driver.php(67): set_aggro()
> > #3 /root/wifi-pineapple-war-driver/war-driver.php(43): run_scand()
> > #4 {main}
> > thrown in /root/wifi-pineapple-war-driver/war-driver.php on line 149`

So I figured out the solution to this and it's just a basic change to the documentation. I figured out that on my Kali Linux install I needed the dependency php-curl.
Running "apt-get install php-curl" and then trying the script again fixed my problem.
